# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91c0dc69c3b102a299021116626a55ed45de47404b887dc5d3099752246da047d0c38414fa16540b098fd6036d050a41ada8654ddecde55f5f077c174dd1be57

test:
  secret_key_base: cafce4ffa1e7d03bf9ca955484046e6213d426ee032a01274bb1f5fc7cafd26b9728aa68e699873667b7c23cd9f6e440397593614a36fa887f8c86e87f2c4b4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
